services:
  configserver:
    image: "jcarjunreddy/configserver:s8"
    container_name: "configserver-ms"
    ports:
      - "8071:8071"
    healthcheck:
      test: "curl --fail --silent localhost:8071/actuator/health/readiness | grep UP || exit 1"
      interval: 10s
      timeout: 5s
      retries: 10
      start_period: 10s
    extends:
      file: common-config.yml
      service: microservice-base-config

  eurekaserver:
    image: "jcarjunreddy/eurekaserver:s8"
    container_name: "eurekaserver-ms"
    ports:
      - "8070:8070"
    healthcheck:
      test: "curl --fail --silent localhost:8070/actuator/health/readiness | grep UP || exit 1"
      interval: 10s
      timeout: 5s
      retries: 10
      start_period: 10s
    extends:
      file: common-config.yml
      service: microservice-configserver-config
    environment:
      SPRING_APPLICATION_NAME: "eurekaserver"

  accounts1:
    image: "jcarjunreddy/accounts:s8"
    container_name: "accounts-ms1"
    ports:
      - "8080:8080"
    networks:
      - bankms
    environment:
      SPRING_APPLICATION_NAME: "accounts"
    extends:
      file: common-config.yml
      service: microservice-eureka-config

  accounts2:
    image: "jcarjunreddy/accounts:s8"
    container_name: "accounts-ms2"
    ports:
      - "8081:8080"
    networks:
      - bankms
    environment:
      SPRING_APPLICATION_NAME: "accounts"
    extends:
      file: common-config.yml
      service: microservice-eureka-config

  loans1:
    image: "jcarjunreddy/loans:s8"
    container_name: "loans-ms1"
    ports:
      - "8090:8090"
    environment:
      SPRING_APPLICATION_NAME: "loans"
    extends:
      file: common-config.yml
      service: microservice-eureka-config

  loans2:
    image: "jcarjunreddy/loans:s8"
    container_name: "loans-ms2"
    ports:
      - "8091:8090"
    environment:
      SPRING_APPLICATION_NAME: "loans"
    extends:
      file: common-config.yml
      service: microservice-eureka-config


  cards:
    image: "jcarjunreddy/cards:s8"
    container_name: "cards-ms"
    ports:
      - "9000:9000"
    environment:
      SPRING_APPLICATION_NAME: "cards"
    extends:
      file: common-config.yml
      service: microservice-eureka-config

networks:
  bankms:
    driver: "bridge"